#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    Oct 27, 2019 12:17:59 AM CST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global c960value
    c960value = tk.StringVar()
    global c960pos
    c960pos = tk.StringVar()

def Cancel():
    print('c960confirm_support.Cancel')
    sys.stdout.flush()

def confirm():
    print('c960confirm_support.confirm')
    sys.stdout.flush()

def scroll():
    print('c960confirm_support.scroll')
    sys.stdout.flush()

def spin(p1):
    print('c960confirm_support.spin')
    print('p1 = {0}'.format(p1))
    sys.stdout.flush()

def text(p1):
    print('c960confirm_support.text')
    print('p1 = {0}'.format(p1))
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import c960confirm
    c960confirm.vp_start_gui()




