#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    Oct 27, 2019 12:17:59 AM CST  platform: Windows NT

import c960confirm
from random import randint
from chess960 import num_to_pos, pos_to_num, get_c960_cols
from tkinter import Event

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

c960value = None  # type: tk.StringVar
c960pos = None  # type: tk.StringVar
w = None    # type: c960confirm.ConfirmWindow


def set_Tk_var():
    global c960value, c960pos
    c960value = tk.StringVar()
    c960pos = tk.StringVar()
    c960value.set("518")
    c960pos.set("rnbqkbnr")


def update_pos():
    pos = num_to_pos(int(c960value.get()))
    c960pos.set(pos)
    w.Button1.configure(state="normal")


def update_value():
    value = str(pos_to_num(c960pos.get()))
    c960value.set(value)
    w.Button1.configure(state="normal")


# events
def Cancel():
    destroy_window()


def Random():
    c960value.set(randint(1, 960))
    update_pos()


def Confirm():
    if w.Button1.cget("state") == "disabled":
        return    # to deal with enter key
    w.Result = get_c960_cols(c960pos.get())
    destroy_window()


def scroll():
    update_pos()


def spin(event: Event):
    value = c960value.get()
    try:
        assert int(value) > 0
    except:
        c960value.set("")
        value = ""
    if not value:
        w.Button1.configure(state="disabled")
        return
    value = min(int("".join(filter(lambda x: x.isdigit, value))[:3]), 960)  # 最大3位，最大960
    c960value.set(value)
    update_pos()


def text(event: Event):
    if event.keycode == 13:
        return Confirm()
    w.Button1.configure(state="disabled")
    pos = c960pos.get()
    pos = "".join([x for x in pos.lower() if x in "kqrbn"][:8])
    c960pos.set(pos)
    if len(pos) == 8:
        if sorted(pos) != list("bbknnqrr"):
            c960pos.set("棋子个数不对")
            return
        if not pos.index("r") < pos.index("k") < pos.rindex("r"):
            c960pos.set("车需要在王两边")
            return
        if not (pos.index("b") + pos.rindex("b")) % 2 == 1:
            c960pos.set("两个象需要异色")
            return
        update_value()


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None
