#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    Oct 31, 2019 12:36:36 AM CST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

WhiteMinEntry = BlackMinEntry = WhiteSecEntry = BlackSecEntry = WhiteIncEntry = BlackIncEntry = Cmv = CpuUnit = \
    CpuRebal = CpuSet = Sync = None    # type: tk.StringVar


def set_Tk_var():
    global WhiteMinEntry
    WhiteMinEntry = tk.StringVar(value="5")
    global BlackMinEntry
    BlackMinEntry = tk.StringVar(value="5")
    global WhiteSecEntry
    WhiteSecEntry = tk.StringVar(value="0")
    global BlackSecEntry
    BlackSecEntry = tk.StringVar(value="0")
    global WhiteIncEntry
    WhiteIncEntry = tk.StringVar(value="3")
    global BlackIncEntry
    BlackIncEntry = tk.StringVar(value="3")
    global Cmv
    Cmv = tk.StringVar(value="UseDepth")
    global CpuUnit
    CpuUnit = tk.StringVar(value="步(半回合)")
    global CpuRebal
    CpuRebal = tk.StringVar(value="1.0")
    global CpuSet
    CpuSet = tk.StringVar(value="16")
    global Sync
    Sync = tk.BooleanVar(value=True)


def SynSet():
    print('clockconfirm_support.Syn')
    sys.stdout.flush()


def Cancel():
    print('clockconfirm_support.Cancel')
    sys.stdout.flush()


def Confirm():
    print('clockconfirm_support.Confirm')
    sys.stdout.flush()


def Default():
    print('clockconfirm_support.Default')
    sys.stdout.flush()


def OptionChange():
    print('clockconfirm_support.OptionChange')
    print(Cmv.get())
    sys.stdout.flush()


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


if __name__ == '__main__':
    import clockconfirm

    clockconfirm.vp_start_gui()
