#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    Nov 06, 2019 11:09:03 PM CST  platform: Windows NT

import sys
from typing import List
from tkinter import CallWrapper
from setboard_global import Globals
from consts import Pieces

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

PName = FlipVar = C960switch = RrCol = LrCol = None  # type: tk.StringVar
Wkcast = Wqcast = Bkcast = Bqcast = None    # type: tk.IntVar
CellValues = None  # type: List[List[tk.StringVar]]


def set_Tk_var():
    global PName, FlipVar, CellValues, C960switch, RrCol, LrCol, Wkcast, Wqcast, Bkcast, Bqcast
    PName = tk.StringVar(value="K")
    FlipVar = tk.StringVar(value='翻转局面')
    CellValues = [[tk.StringVar(value="") for _ in range(8)] for _ in range(8)]
    C960switch = tk.StringVar(value="normal")
    RrCol = tk.StringVar(value="H")
    LrCol = tk.StringVar(value="A")
    C960switch.trace_variable("w", c960_switch_callback)
    Wkcast = tk.IntVar(value=1)
    Wqcast = tk.IntVar(value=1)
    Bkcast = tk.IntVar(value=1)
    Bqcast = tk.IntVar(value=1)


def debug():    # todo: remove
    print(C960switch.get())


def c960_switch_callback(*args):
    main = Globals.Main
    if C960switch.get() == "c960":
        main.KingSide.configure(state='normal')
        main.QueenSide.configure(state='normal')
    else:
        main.KingSide.configure(state='disabled')
        main.QueenSide.configure(state='disabled')


def cancel():
    print('setboard_support.cancel')
    sys.stdout.flush()


def clear():
    print('setboard_support.clear')
    sys.stdout.flush()


def confirm():
    print('setboard_support.confirm')
    sys.stdout.flush()


def copy():
    print('setboard_support.copy')
    sys.stdout.flush()


def flip():
    print('setboard_support.flip')
    sys.stdout.flush()


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def cell_click(event: CallWrapper) -> None:
    r, c = Globals.Reverse_cell_names[str(event.widget)]
    piece = PName.get()
    if Globals.Board_array[r][c] == piece:
        Globals.Board_array[r][c] = None
        CellValues[r][c].set("")
    else:
        Globals.Board_array[r][c] = piece
        CellValues[r][c].set(Pieces[piece])


if __name__ == '__main__':
    import setboard

    setboard.vp_start_gui()
