#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Nov 13, 2019 05:32:12 PM CST  platform: Windows NT
from typing import Dict, Union, List
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk
try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

if (lambda: None)():
    import uci_chart

w = None  # type: uci_chart.Toplevel1


def cancel():
    destroy_window()


def choose(event):
    if not w.Scrolledtreeview1.selection():
        return
    chosen = w.Scrolledtreeview1.item(w.Scrolledtreeview1.selection()[0])["text"]
    w.Result = chosen
    destroy_window()


def init(top, gui, pgns: List[Dict[str, Union[Dict, str]]]):
    global w, top_level, root
    w = gui  # type: uci_chart.Toplevel1
    top_level = top
    root = top
    columns = w.Columns
    for i, pgn in enumerate(pgns):
        pgn_small = {k.lower(): v for k, v in pgn.get("header").items()}
        if pgn_small.get("variant") and pgn_small.get("variant").lower() in ("chess960", "fischerandom"):
            pgn_small["eco"] = "Chess960"
        w.Scrolledtreeview1.insert("", "end", text=str(i), values=[pgn_small.get(k) or "" for k in columns])


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None
