#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    Oct 06, 2019 11:52:10 PM CST  platform: Windows NT

import sys
from verachess_global import Globals
from typing import List, Tuple
from verachess import Color
from consts import Pieces
from tkinter import CallWrapper
import events


try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

CellValues = None    # type: List[List[tk.StringVar]]


def set_Tk_var():
    global CellValues
    CellValues = [[tk.StringVar(value="") for _ in range(8)] for _ in range(8)]


def set_cell_values(narrow_fen: str):
    rows = narrow_fen.split("/")
    assert len(rows) == 8, "error fen"
    for i, row in enumerate(rows):
        j = 0
        for char in row:
            if char in Pieces:
                CellValues[i][j].set(Pieces[char])
                j += 1
            else:
                [CellValues[i][r].set("") for r in range(j, j + int(char))]
                j += int(char)    # if this errors, char is illegal


def set_cell_color(color_cell: Tuple[Tuple[int, int], str] = None, flush_all=False):
    """
    :param color_cell: [(x, y), colors]
    :param flush_all: flush other cells with black
    :return:
    """
    main = Globals.Main
    if flush_all:
        [main.Cells[cell_r][cell_c].configure(foreground=Color.black) for cell_r in range(8) for cell_c in range(8)]
    if color_cell[0]:
        (cell_r, cell_c), color = color_cell
        main.Cells[cell_r][cell_c].configure(foreground=color)


def set_cell_back_colors(active_color_list: List[Tuple[int, int]] = None, inactive_color_list: List[Tuple[int, int]] =
        None, flush_all=False):
    """
    :param active_color_list: 
    :param inactive_color_list: 
    :param flush_all: 
    :return: 
    """
    main = Globals.Main
    if flush_all:
        [main.Cells[r][c].configure(background=Color.lemon_dark if (r + c) % 2 else Color.lemon_light) for r in range(8)
         for c in range(8)]
    if inactive_color_list:     # deselect old first
        for r, c in inactive_color_list:
            main.Cells[r][c].configure(background=Color.lemon_dark if (r + c) % 2 else Color.lemon_light)
    if active_color_list:
        for r, c in active_color_list:
            main.Cells[r][c].configure(background=Color.cell_sel_dark if (r + c) % 2 else Color.cell_sel_light)


def exit():
    print('verachess_support.exit')
    sys.stdout.flush()


def cell_click(event: CallWrapper) -> None:
    if Globals.Game_end:
        return
    place = Globals.Reverse_cell_names[str(event.widget)]
    # todo: change color to background too
    if Globals.Selection == place:
        Globals.Selection = None
        set_cell_color(color_cell=(place, Color.black))
        events.refresh_highlights()
    else:
        after = events.cell_click_handler(Globals.Selection, place)     # the click place, except castle in c960
        if after is not None:
            set_cell_color(color_cell=(place, Color.blue))
        set_cell_color(color_cell=(Globals.Selection, Color.black))
        Globals.Selection = after


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None
